### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by rioj7** [tomaszs/Assistant#2]
`src/CodelensProvider.ts`

line 33, 40 : Why create a regex from an already created regex (line 23)

line 34: how likely is it that the text of the document changes while processing the regexes

line 37,38,39: `document.positionAt()` already gives you a complete `Position`

```
let position = document.positionAt(matches.index);
```

How do I enter a regex with the flag `i`

It is possible in `package.json` to specify the allowed format of the configuration, allowed field names and types.

**Comment by tomaszs** [comment]
@rioj7 Thanks!

**Comment by tomaszs** [comment]
@rioj7 how do you pecify allowed format of configuration etc. in package.sjon?

**Comment by tomaszs** [comment]
implemented.
Now RegEx flags (modifiers) can be set rule level and workspace level. Details in the readme
